'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My


	<System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")>
	Friend NotInheritable Partial Class Settings
		Inherits System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = (CType(System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property

		<System.Configuration.ApplicationScopedSettingAttribute()>
		<System.Diagnostics.DebuggerNonUserCodeAttribute()>
		<System.Configuration.SpecialSettingAttribute(System.Configuration.SpecialSetting.ConnectionString)>
		<System.Configuration.DefaultSettingValueAttribute("Data Source=|DataDirectory|\Database1.sdf")>
		Public ReadOnly Property Database1ConnectionString() As String
			Get
				Return (DirectCast(Me("Database1ConnectionString"), String))
			End Get
		End Property
	End Class
End Namespace
